export const designSystem = {
    units: {
        xxs: "var(--space-2xs)",
        xs: "var(--space-xs)",
        sm: "var(--space-sm)",
        md: "var(--space-md)",
        lg: "var(--space-lg)",
        xl: "var(--space-xl)",
        xxl: "var(--space-2xl)",
        xxxl: "var(--space-3xl)",
        xxxxl: "var(--space-4xl)",
    },
    sizes: {
        five: "5%",
        ten: "10%",
        twenty: "20%",
        twentyFive: "25%",
        fifty: "50%",
        seventyFive: "75%",
        eighty: "80%",
        ninety: "90%",
        hundred: "100%",
        sidebar: "var(--size-sidebar-width)",
        buttonHeight: "var(--size-button-height)",
        iconSm: "var(--size-icon-sm)",
        iconMd: "var(--size-icon-md)",
        iconLg: "var(--size-icon-lg)",
        logo: "var(--size-logo)",
    },
    colors: { 
        primary: "var(--color-primary)",
        primaryHover: "var(--color-primary-hover)",
        primarySoft: "var(--color-primary-soft)",
        primaryTinted: "var(--color-primary-tinted)",
        primaryRing: "var(--color-primary-ring)",
        secondary: "var(--color-secondary)",
        secondarySoft: "var(--color-secondary-soft)",
        accent: "var(--color-accent)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        error: "var(--color-error)",
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        surfaceRaised: "var(--color-surface-raised)",
        surfaceMuted: "var(--color-surface-muted)",
        sidebar: "var(--color-sidebar)",
        contrast: "var(--color-surface)",
        border: "var(--color-border)",
        borderStrong: "var(--color-border-strong)",
        textPrimary: "var(--color-text)",
        textSecondary: "var(--color-text-muted)",
        textSoft: "var(--color-text-soft)",
        textInverse: "var(--color-text-inverse)",
        itemBackground: "var(--color-item-background)",
        itemHover: "var(--color-item-hover-background)",
        itemActiveBackground: "var(--color-item-active-background)",
        itemActiveText: "var(--color-item-active-text)",
        disabledBackground: "var(--color-disabled-background)",
    },
    radii: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        pill: "var(--radius-pill)",
    },
    shadows: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
    },
    transitions: {
        fast: "var(--transition-fast)",
    },
    typography: {
        fontFamily: "var(--font-family-sans)",
        fontSizeXs: "var(--font-size-xs)",
        fontSizeSm: "var(--font-size-sm)",
        fontSizeMd: "var(--font-size-md)",
        fontSizeLg: "var(--font-size-lg)",
        fontSizeXl: "var(--font-size-xl)",
        fontSize2xl: "var(--font-size-2xl)",
        fontWeightRegular: "var(--font-weight-regular)",
        fontWeightMedium: "var(--font-weight-medium)",
        fontWeightSemibold: "var(--font-weight-semibold)",
        fontWeightBold: "var(--font-weight-bold)",
        lineHeightTight: "var(--line-height-tight)",
        lineHeightNormal: "var(--line-height-normal)",
    }
} as const;
